### ISSUE TITLE
Getting error when trying to deploy into testnet using beaker

### ISSUE THREAD

**Issue by sbnair** [osmosis-labs/osmosis-rust#18]
I am getting this error :
Error: status: Unknown, message: "failed to execute message; message index: 0: Error calling the VM: Error during static Wasm validation: Wasm contract requires unsupported import: \"__wbindgen_placeholder__.__wbindgen_describe\". Required imports: {\"__wbindgen_externref_xform__.__wbindgen_externref_table_grow\", \"__wbindgen_externref_xform__.__wbindgen_externref_table_set_null\", \"__wbindgen_placeholder__.__wbindgen_describe\", ... 15 more}. Available imports: [\"env.abort\", \"env.db_read\", \"env.db_write\", \"env.db_remove\", \"env.addr_validate\", \"env.addr_canonicalize\", \"env.addr_humanize\", \"env.secp256k1_verify\", \"env.secp256k1_recover_pubkey\", \"env.ed25519_verify\", \"env.ed25519_batch_verify\", \"env.debug\", \"env.query_chain\", \"env.db_scan\", \"env.db_next\"].: create wasm contract failed", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "5966256"} }

when i am using this command 
beaker wasm deploy osmosis-stargate --signer-account test1 --no-wasm-opt --admin signer --raw '{}' --network testnet

pls help, it seems there is some library used in this project having problems with wasm-gen, pls let me know.

**Comment by iboss-ptk** [comment]
this is fixed by `v0.1.4` please see #21 if you want to know more details :) Please open new issue if it's still a problem
