### ISSUE TITLE
is there any way to deposit and withdraw osmo or atom ?

### ISSUE THREAD

**Issue by sbnair** [osmosis-labs/osmosis-rust#19]
is there any examples with cosmwasm smart contracts in osmosis which works related to deposit/withdraw functionality of osmo tokens ?

**Comment by iboss-ptk** [comment]
@sbnair could you give more context about it? do you mean IBC-ing in and out of the chain or some other thing?

**Comment by iboss-ptk** [comment]
the issue has been inactive, will close this now and if you have any question, please reopen this again
