### ISSUE TITLE
Upgrade to latest tendermint-proto (or pin `time` dependency)

### ISSUE THREAD

**Issue by nicolaslara** [osmosis-labs/osmosis-rust#21]
Osmosis-std uses a version of tendermint-proto that ends up depending on wasmbindgen. See https://github.com/osmosis-labs/swaprouter/pull/1

Until a new release of cosmos-sdk-proto is made, we should pin tendermint proto to either `v0.23.9` or `v0.24.0-pre.2`. Alternatively, pin `time` directly via `time = { version = ">=0.3, <0.3.12", default-features = false, features = ["std"] }`

**Comment by nicolaslara** [comment]
Created a PR on cosmos-rust for fixing this upstream: https://github.com/cosmos/cosmos-rust/pull/271

**Comment by iboss-ptk** [comment]
I remove cosmos-sdk-proto since it's not needed for now, and when this lib supports non cosmwasm work, I will add feature flag for them. Thanks for the help @nicolaslara !
