### ISSUE TITLE
Queriers should not take ownership of `QuerierWrapper`

### ISSUE THREAD

**Issue by larry0x** [osmosis-labs/osmosis-rust#36]
Currently queriers such as `GammQuerier` takes ownership of a `QuerierWrapper` object. I'm wondering if it's possible to let it take a reference instead:

```diff
pub struct GammQuerier<'a> {
-   querier: QuerierWrapper<'a, Empty>,
+   querier: &'a QuerierWrapper<'a, Empty>,
}
```

This way we avoid cloning the querier wrapper when creating multiple queriers, which saves gas.

**Comment by iboss-ptk** [comment]
Nice catch! Thank you :D @larry0x
