### ISSUE TITLE
Add CI to automate update of `osmosis-main-clone` branch

### ISSUE THREAD

**Issue by ValarDragon** [osmosis-labs/osmosis-rust#39]
We need to make a cron Action job to automate commits to the `osmosis-main-clone` branch, to update the git submodule code + generate the changes,

Steps:
- Make cron CI job + manual trigger. Job should
- git checkout osmosis-main-clone
- Make it do `git submodule update --remote`
- `cargo install proto-build --path=.`
- $IF_CHANGE , commit from osmo-bot

**Comment by iboss-ptk** [comment]
@ValarDragon please note [this commit](https://github.com/osmosis-labs/osmosis-rust/commit/1e849f71eac94365aaee44915d6506923e09e14d) I manually patch one struct that depends on tendermint proto. To really fix this problem we need to generate tendermint structs ourselves, but currently the code gen is not as complete as I would like it to be. Planning to fix it along side with  #12 .

Also I think `cargo build -p osmosis-std` should be a step in CI to check if the generated code compiles.

on the side note. `cargo run -- --update-deps` run submodule update as well.


Let me know if you get stuck.

**Comment by iboss-ptk** [comment]
I Will add auto patch for `HistoricalInfo` for now so this brach auto generated code compiles

**Comment by iboss-ptk** [comment]
The patch is available now with [this commit ](https://github.com/osmosis-labs/osmosis-rust/commit/4121bfe92932cbf9183625fb883f97b5b740b2a4)!

**Comment by iboss-ptk** [comment]
same as #14
