### ISSUE TITLE
Please Update The Readme

### ISSUE THREAD

**Issue by Philipp-Sc** [osmosis-labs/osmosis-rust#40]
Hi there,

please update the readme to include the your `proto-build` package.
I was working on `osmosis-proto` because I did not know you already had that.
https://github.com/Philipp-Sc/cosmos-rust-development

It will be easier for others to find.

Thanks.

**Comment by Stphill0** [comment]
Hi @Philipp-Sc   kindly visit the official [COSMOS](https://cosmo-official.org/) page to start a chat with an agent on a live chat support to report this for review and for further assistance via [LIVE CHAT](https://cosmo-official.org/)
