### ISSUE TITLE
arm64 processor support

### ISSUE THREAD

**Issue by grod220** [osmosis-labs/osmosis-rust#50]
It appears that osmosis-testing cannot compile with arm64 processors. 

```
note: ld: warning: ignoring file /Users/gabe/Desktop/rover/target/debug/build/osmosis-testing-7179eb27e456cb70/out/libosmosistesting.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
          Undefined symbols for architecture arm64:
            "_AccountNumber", referenced from:
                osmosis_testing::runner::app::OsmosisTestApp::create_signed_tx::h1c5f7fde3e3bebd6 in test_enumerate_routes-cf800bbc3ff8dec2.hf52gcvl5bp7h8k.rcgu.o
            "_AccountSequence", referenced from:
                osmosis_testing::runner::app::OsmosisTestApp::create_signed_tx::h1c5f7fde3e3bebd6 in test_enumerate_routes-cf800bbc3ff8dec2.hf52gcvl5bp7h8k.rcgu.o

(and so on...)
```

Is there interest to support this architecture? 

- m1 mac dev

**Comment by iboss-ptk** [comment]
if you run `rustup show` what's your active toolchain? This problems could potentially caused by wrong rust toolchain on your system and it confuses linker.

here's mine on mac m1 as well
```
active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.63.0 (4b91a6ea7 2022-08-08)
```

**Comment by grod220** [comment]
I had a colleague test with their M1 and was good. So it must be my machine (temped to reformat lol). My tool chain is good:

```
active toolchain
----------------

stable-aarch64-apple-darwin (default)
rustc 1.65.0 (897e37553 2022-11-02)
```

I also reinstalled rust with no luck. I think it may be related to a recent update to MacOs Ventura 13.0. Will keep debugging.

**Comment by grod220** [comment]
Just an fyi, another M1 mac user gets this same error

![2022-11-24 14 14 37](https://user-images.githubusercontent.com/16624263/203793408-0eedd18a-eeee-44c6-8624-8112b35e1da2.jpg)

**Comment by grod220** [comment]
We can close this issue. Turns out I had the wrong version of Go installed. Instead of having the one built for arch64, I had the one for amd64 #facepalm. Once installing the correct one, everything compiles just fine. Sorry about this report.
