### ISSUE TITLE
Querying Pools ::decode

### ISSUE THREAD

**Issue by triccs** [osmosis-labs/osmosis-rust#51]
![image](https://user-images.githubusercontent.com/105668529/200175768-6bb536ef-a434-4e50-854e-9e500d6fb55c.png)
I'm trying to implement this example from (https://github.com/osmosis-labs/osmosis-rust/tree/main/packages/osmosis-std#querying-pool) but I can't get `decode()` to work.

This is the error but prost::message::Message is private and prost::Message is flagged as an "unused import".
![image](https://user-images.githubusercontent.com/105668529/200175899-538e8fc6-0e95-45a9-85fd-8d71cd0b7c9b.png)

Apologize for my ignorance but I'm not sure how to solve this.

**Comment by iboss-ptk** [comment]
Have you tried `use prost::Message`? `decode` is a `Message` trait's method.
