### ISSUE TITLE
TWAP test failed on "looking for a time thats too old"

### ISSUE THREAD

**Issue by iboss-ptk** [osmosis-labs/osmosis-rust#53]
With the following code:

```rust
pub fn test_twap(deps: Deps, env: Env) -> StdResult<TestTwapResponse> {
    let start_time = env.block.time.minus_seconds(300);
    let start_time = OsmosisTimestamp {
        seconds: start_time.seconds() as i64,
        nanos: 0_i32,
    };

    let twap = TwapQuerier::new(&deps.querier)
        .arithmetic_twap_to_now(
            2,
            "uosmo".to_string(),
            "uatom".to_string(),
            Some(start_time.clone()),
        )?
        .arithmetic_twap;

    Ok(TestTwapResponse { price: twap })
}
```

This error can occur
```
QueryError { msg: "looking for a time thats too old, not in the historical index.  Try storing the accumulator value. (requested time 2022-10-26 20:09:03 +0000 UTC)" }
```

This might be caused by block time issue. To know for sure check
- [twap/store.go](https://github.com/osmosis-labs/osmosis/blob/6e848972cdef5e46ddafdc7eb268eebade9c9168/x/twap/store.go#L185-L213)

**Comment by iboss-ptk** [comment]
First, we need at least 2 swaps to create historical index.

Second, With current implementation every execution creates new block and [block timestamp will +5 secs from last block](https://github.com/osmosis-labs/osmosis-rust/blob/9b010acf59d631cf099f2b45dbc011a4d99b37f8/packages/osmosis-testing/libosmosistesting/testenv/setup.go#L135). 

[working example can be found here](https://github.com/osmosis-labs/osmosis-rust/blob/osmosis-testing/twap-example/tests/osmosis-std-cosmwasm-test/tests/integration_test.rs#L176-L227). From genesis to latest, every execution +5 secs on block time, so the twap query needs to compensate them to be right in the range.

For more sophisticated block time control will be separated to another issue.

**Comment by piobab** [comment]
@iboss-ptk
I modified your example to show a problem with custom twap module. The price is not deserialized correctly. Please take a look on this commit https://github.com/piobab/osmosis-rust/commit/3e10178038f6d2da2e997e65e837fe6a220f99f0

`left: `"0.944009649029192124"`, right: `"944009649029192124"`'`

**Comment by iboss-ptk** [comment]
created new issue to track this https://github.com/osmosis-labs/osmosis-rust/issues/59
