### ISSUE TITLE
Issue with osmosis.poolmanager.v1beta1.MsgSwapExactAmountIn

### ISSUE THREAD

**Issue by tandn37** [osmosis-labs/osmosis-rust#76]
I'm switching from **gamm.v1beta1.MsgSwapExactAmountIn** to **poolmanager.v1beta1.MsgSwapExactAmountIn** but got this error when broadcast the message (via cosmwasm) on osmosis local.

The message is constructed using **osmosis-rust/osmosis-std** branch **autobuild-main** (since we don't have v15 yet)
`
-> CosmosMsg {
  let route = SwapAmountInRoute {
    pool_id,
    token_out_denom
  };
  MsgSwapExactAmountIn {
      sender
      routes
      token_in
      token_out_min_amount
  }.into()
}
`

Error after sending the message: 

`Error: status: Unknown, message: "failed to execute message; message index: 0: dispatch: submessages: Cannot unpack proto message with type URL: /osmosis.poolmanager.v1beta1.MsgSwapExactAmountIn: invalid CosmosMsg from the contract", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "33829"} }`

The **gamm.v1beta1.MsgSwapExactAmountIn** work fine.
Is this library issue or issue with the chain?
Should I stick to **gamm.v1beta1.MsgSwapExactAmountIn**? Will it be deprecated in the future?

**Comment by iboss-ptk** [comment]
`gamm.v1beta1.MsgSwapExactAmountIn` will be deprecated in the future, please update localosmosis, which version are you on?

**Comment by tandn37** [comment]
@iboss-ptk oh I forgot to close the issue, it's the chain issue.
