### ISSUE TITLE
Please document Bank.MsgSend.from_address possible values

### ISSUE THREAD

**Issue by dzmitry-lahoda** [osmosis-labs/osmosis-rust#81]
is that value can be anything when called from permission less CW contract?

https://github.com/osmosis-labs/osmosis-rust/blob/b78e29b7d6b7e21d8024f13a24820cc040646b6f/packages/osmosis-std/src/types/cosmos/bank/v1beta1.rs#L707

or some checks are done?

if behavior is different for permissions and permissioned contracts, how to check if my contract is one of two?

**Comment by dzmitry-lahoda** [comment]
i found only send token approval for now. any other authorization kind? full proxy to do any spending any time?

**Comment by iboss-ptk** [comment]
I'm not sure if I understand what you mean but how `MsgSend` works is that it works as it should with [bank module](https://docs.cosmos.network/v0.47/modules/bank#messages). And `from_address` should be contract address since it's the sender.

**Comment by dzmitry-lahoda** [comment]
question is what if cw contract will set here non contract address?

**Comment by iboss-ptk** [comment]
could you elaborate? @dzmitry-lahoda
