### ISSUE TITLE
Question: Is this repository MIT OR Apache-2.0 licensed or not?

### ISSUE THREAD

**Issue by loloicci** [osmosis-labs/osmosis-rust#86]
In this repository, some of https://github.com/osmosis-labs/osmosis-rust/tree/main/packages are licensed as MIT OR Apache-2.0, but other files look not clearly licensed.
Is this repository licensed, or not? If it is not licensed, could you add some licenses to this repository if you will add licenses to it?

**Comment by iboss-ptk** [comment]
It is! I have added dual licenses (APACHE 2.0 + MIT). Enjoy :)
